config/routes.rb
Rails.application.routes.draw do
  resources :problems
  resources :projects
  devise_for :users

  devise_scope :user do
  	get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
  	get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: 'pages#index'


  #############################MESSAGE ROUTES ###########################
  post '/messages/new', to: 'pages#create_message', as:'message_create'
  get 'messages', to: 'pages#list_messages'
  get 'messages/:id', as: 'message', to: 'pages#show_message'



  ############################NEWSLETTER EMAIL LIST ####################
  post 'addingemail', to: 'pages#add_email_to_list', as:'add_email'



###############################API ###################################
  get 'json', as:'json', to: 'api#index'
  get 'temp', as:'temp', to: 'api#temp'



end

app/models/problem.rb
class Problem < ApplicationRecord
	belongs_to :language

	# CASE SENSITIVE form fields.
	#name, from, description
	validates :name, :from, :description, :language_id, presence: true
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  layout 'problem'
  before_action :set_problem, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /problems
  def index
    @problems = Problem.all.order(name: :desc)
  end

  # GET /problems/1
  def show
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  def create
    @problem = Problem.new(problem_params)

    if @problem.save
      redirect_to @problem, notice: 'Problem was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /problems/1
  def update
    if @problem.update(problem_params)
      redirect_to @problem, notice: 'Problem was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /problems/1
  def destroy
    @problem.destroy
    redirect_to problems_url, notice: 'Problem was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def problem_params
      params.require(:problem).permit(:name, :from, :description, :code, :language_id)
    end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.erb
<%= form_with(model: problem, local: true) do |form| %>
  <% if problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.text_field :name,  class: "form-control", placeholder:"Name" %>
  </div>

  <div class="form-group">
    <%= form.text_field :from,  class: "form-control", placeholder:"From (eg: Project Euler)"%>
  </div>

  <div class="form-group">
    <%= form.text_area :description,  class: "form-control", placeholder:"Description", rows: "7" %>
  </div>

  <div class="form-group">
    <%= form.text_area :code,  class: "form-control", placeholder:"Insert Code Here", rows: "17" %>
  </div>

  <div class="form-group">
    <%= form.select(:language_id, options_from_collection_for_select(Language.all.order(:name), :id, :name), {}, {class: "form-control"}) %>
  </div>

  <div class="actions">
    <%= form.submit "Add Problem", class: "btn btn-orange border-none btn-rounded-corner width-70" %>
  </div>
<% end %>

app/views/problems/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Tag</th>
      <th scope="col">Language</th>
      <%= '<th scope="col"></th>'.html_safe if logged_in?(:admin) %>
    </tr>
  </thead>

  <tbody>
    <% i = 1 %>
    <% @problems.each do |problem| %>
      <tr>
        <th scope="row"><%= i %></th>
        <td><%= link_to problem.name, problem %></td>
        <td><%= problem.from %></td>
        <td><%= problem.language.name %></td>
        <td><%= link_to '<i class="ion-close"></i>'.html_safe, problem, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:admin)%></td>
      </tr>
      <% i = i + 1 %>
    <% end %>
  </tbody>
</table>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<div class = "container padding-top-bottom-60" >
	<h3> Problem Archive </h3>

	<br>

	<%= render 'table' %>
	<hr>


	<%= link_to 'New Problem <i class="ion-android-add"></i>'.html_safe, new_problem_path,  class: "btn btn-orange border-none btn-rounded-corner" if logged_in?(:admin) %>
	<%= link_to '<i class="ion-home"></i> Home'.html_safe, root_url, class: "btn btn-orange border-none btn-rounded-corner" %>
</div>

app/views/problems/new.html.erb
<div class="row">
	<div class="col-md-8">
		<h3>New Problem</h3>

		<%= render 'form', problem: @problem %>

		<%= link_to 'Back', problems_path,  class: "btn btn-danger margin-top-bottom-10" %>

	</div>
</div>

app/views/problems/show.html.erb
<div class="container padding-top-bottom-60">

	<p id="notice"><%= notice %></p>

	 <h3 class="center"><%= @problem.name %></h3>

	<p>
	  <h5><%= @problem.from %></h5>
	</p>

	<p>
		<strong> Description: </strong>
		<%= @problem.description %>
	</p>

	<!-- HTML Box -->
	<div class="codeheader" id="codeheader_html"><%= @problem.language.name %></div>
	<div id="codebox">
		<pre><code data-language="<%= @problem.language.name %>"><%= @problem.code %></code></pre>
	</div>

	<% if logged_in? (:admin) %>
		<%= link_to 'Edit', edit_problem_path(@problem), class: "btn btn-orange border-none btn-rounded-corner" %> |
	<% end %>
	<%= link_to 'Back', problems_path, class: "btn btn-white border-none btn-rounded-corner" %>
</div>