config/routes.rb
Rails.application.routes.draw do
  resources :problems
  resources :projects
  devise_for :users

  devise_scope :user do
  	get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
  	get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: 'pages#index'


  #############################MESSAGE ROUTES ###########################
  post '/messages/new', to: 'pages#create_message', as:'message_create'
  get 'messages', to: 'pages#list_messages'
  get 'messages/:id', as: 'message', to: 'pages#show_message'



  ############################NEWSLETTER EMAIL LIST ####################
  post 'addingemail', to: 'pages#add_email_to_list', as:'add_email'



###############################API ###################################
  get 'json', as:'json', to: 'api#index'
  get 'temp', as:'temp', to: 'api#temp'



end

app/views/shared/_footer.html.erb
<footer id="footer" class="gradient-violat">
  <div class="container-fluid">
    <!-- Row -->
      <div class="row">
        <div class="col-md-12">
           <!-- footer logo -->
          <div class="footer-logo">
            <%= link_to image_tag('Logo.png'), root_path, class: "navbar-brand", method: :get %>
          </div>
          <!-- /footer logo -->
          <!-- footer follow -->
          <ul class="footer-follow">
            <li><%= link_to "<i class=\"ion-social-github\"></i>".html_safe, "https://www.github.com/minhalexus"%>
            <li><%= link_to "<i class=\"ion-social-facebook\"></i>".html_safe, "https://www.facebook.com/mshanjer"%>
            <li><%= link_to "<i class=\"ion-social-instagram\"></i>".html_safe, "https://www.instagram.com/minhalexus"%>
            <li><%= link_to "<i class=\"ion-social-linkedin\"></i>".html_safe, "https://www.linkedin.com/in/mshanjer/"%>
          </ul>
          <!-- /footer follow -->
          <!-- footer copyright -->
          <div class="footer-copyright">
            <b><p class="text-white">© 2018 | Minhal Shanjer All rights reserved</p></b>
          </div>
          <!-- /footer copyright -->
        </div>
      </div>
      <!-- /Row -->
    </div>
    <!-- /Container -->
  </footer>

app/views/shared/_navbar.html.erb
<header id="home" class="gradient-violat">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top navbar-color">
    <div class="container-fluid">
      <%= link_to image_tag('Logo.png'), root_path, class: "navbar-brand", method: :get %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="nav navbar-nav ml-auto"> <!-- <ul class="navbar-nav ml-auto"> -->
          <li class="nav-item">
            <a class="nav-link" href="#introduction">Introduction</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#about">About Me</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#skills">Skills</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#coding-problems">Coding Problems</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#projects">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#contact">Contact Me</a>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", messages_path, class: "nav-link" if logged_in?(:admin) %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" if logged_in?(:admin, :user) %>
          </li>
          <!-- <li><a href="#" class="btn btn-orange border-none btn-rounded-corner btn-navbar">Download<span class="icon-on-button"><i class="ion-ios-cloud-download-outline"></i></span></a></li> -->
        </ul>
      </div>
    </div>
  </nav>
</header> 

app/views/shared/_quicknav.html.erb
<header id="home" class="gradient-violat">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to image_tag('Logo.png'), root_path, class: "navbar-brand", method: :get %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="nav navbar-nav ml-auto"> <!-- <ul class="navbar-nav ml-auto"> -->
          <li class="nav-item">
            <%= link_to 'Projects', projects_path, class:"nav-link", method: :get %>
          </li>
          <li class="nav-item">
            <%= link_to 'Coding Problems', problems_path, class:"nav-link", method: :get %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", messages_path, class: "nav-link" if logged_in?(:admin) %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" if logged_in?(:admin) %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header> 