config/routes.rb
Rails.application.routes.draw do
  resources :problems
  resources :projects
  devise_for :users

  devise_scope :user do
  	get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
  	get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: 'pages#index'


  #############################MESSAGE ROUTES ###########################
  post '/messages/new', to: 'pages#create_message', as:'message_create'
  get 'messages', to: 'pages#list_messages'
  get 'messages/:id', as: 'message', to: 'pages#show_message'



  ############################NEWSLETTER EMAIL LIST ####################
  post 'addingemail', to: 'pages#add_email_to_list', as:'add_email'



###############################API ###################################
  get 'json', as:'json', to: 'api#index'
  get 'temp', as:'temp', to: 'api#temp'



end

app/views/pages/_about.html.erb
<section id="about" class="padding-top-90 padding-bottom-90">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="heading-wraper text-center margin-bottom-25">
            <h4>About Me</h4>
            <hr class="heading-devider gradient-orange">
        </div>
      </div>
      <div class="col-md-4 center">
        <%= image_tag "minhalshanjer.jpg", class: "img-responsive profile-border sm-display-small", alt:"" %> <!-- removed sm-display-none class from imgtag -->
      </div>
      <div class="col-md-4 sm-padding-top-60">
        <div class="row">
          <div class="col-md-12 col-sm-12 padding-top-35">
            <h5 class="service-title">Personal</h5>
            <p class="services-content margin-bottom-25 text-size-15px">Hi, I'm Minhal Shanjer. I study computer science at the University of Waterloo. I fell in love with CS ever since I participated in the Canadian Computing Competition (CCC) in Grade 10. I am currently in my second year of university.</p>
          </div>
          <div class="col-md-12 col-sm-12">
            <h5 class="service-title">Tech Interests</h5>
            <p class="services-content margin-bottom-25 text-size-15px">Web Development | Machine Learning | Software Development | Web Scraping | Virtual Reality </p> 
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="row">
          <div class="col-md-12 col-sm-12 padding-top-35">
            <h5 class="service-title">Some Fun Courses I've Taken</h5>
            <p class="services-content">
              <i class ="ion-ios-information-outline"> </i><%= link_to "CS246: Object-Oriented Software Development", "https://www.student.cs.uwaterloo.ca/~cs246/" %> <br>
              <i class ="ion-ios-information-outline"> </i><%= link_to "Dissecting Ruby on Rails 5 - Become a Professional Developer", "https://www.udemy.com/professional-rails-5-development-course/" %><br>
              <i class ="ion-ios-information-outline"> </i><%= link_to "Android O & Java - The Complete Android Development Bootcamp", "https://www.udemy.com/android-app-development-with-java/" %><br>
              <i class ="ion-ios-information-outline"> </i><%= link_to "CS136: Elementary Algorithm Design and Data Abstraction", "https://www.student.cs.uwaterloo.ca/~cs136/" %><br>
              <i class ="ion-ios-information-outline"> </i><%= link_to "CS135: Designing Functional Programs", "https://www.student.cs.uwaterloo.ca/~cs135/" %></p><br>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_coding-problems.html.erb
<section id="coding-problems" class="padding-top-bottom-120 bg-image-fit-100 dark-background">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="heading-wraper text-center margin-bottom-25">
            <h4>Coding Problems</h4>
            <hr class="heading-devider gradient-orange">
        </div>
      </div>
      <div class="col-md-6">
        <% @problems.each do |problem| %>
          <div class="feature-wiget">
            <div class="icon-wraper">
              <h5 class="bottom-line"><i class="ion-code special-code-icon"></i><%= link_to problem.name, problem %></h5>
            </div>
            <div class="content">
              <h6><%= problem.from %></h6>
              <p class="character-limit-250"><%= problem.description %></p>
            </div>
          </div>
        <% end %>

        <div class="cta-btn-group">
          <%= link_to problems_url, class: "btn btn-blue border-none btn-rounded-corner width-archive-btn" do %>
                See Full Archive <span class="icon-on-button"><i class="ion-ios-arrow-thin-right"></i></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_contact.html.erb
<section id="contact" class="padding-top-bottom-90 newsletter bg-image-fit-100" style="background: radial-gradient(top left, #0cedff, #9dd35c); /*Standard*/">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="heading-wraper text-center margin-bottom-25">
            <h4>Contact Me</h4>
            <hr class="heading-devider gradient-orange">
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12 padding-top-35">
            <div class="subscription-wraper text-center">
              <h4 class="text-upper">Send A Message</h4>
              <p>Please feel free to add addtional contact details.</p>
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-1"></div>

      <div class="col-md-5 relative-div">
        <div class="row">
          <div class="col-md-12 padding-top-35">
            <div class="subscription-wraper text-center">
              <h4 class="text-upper">Newsletter</h4>
              <p>Stay updated with new content.</p>
              <%= render 'newsletter-form' %>
            </div>
          </div>

          <div class="col-md-12 padding-top-90">
              <h4 class="text-upper text-center">Email Address</h4>
              <p class="text-center">Please no solicitation!</p>
              <p class="contact-email text-center">
                mashanje@uwaterloo.ca
                <br>
                mshanjer@gmail.com
              </p>
          </div>



          <div class="bottom-right sm-display-none">
            <div class="col-md-12 sm-display-none">
              <ul class="footer-follow-v">
                <li><%= link_to "<i class=\"ion-social-github\"></i>".html_safe, "https://www.github.com/minhalexus"%>
                <li><%= link_to "<i class=\"ion-social-facebook\"></i>".html_safe, "https://www.facebook.com/mshanjer"%>
                <li><%= link_to "<i class=\"ion-social-instagram\"></i>".html_safe, "https://www.instagram.com/minhalexus"%>
                <li><%= link_to "<i class=\"ion-social-linkedin\"></i>".html_safe, "https://www.linkedin.com/in/mshanjer/"%>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_cta.html.erb
<section id="cta" class="gradient-violat cta padding-top-bottom-90">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h3 class="cta-heading text-white">GIT CHECKOUT -B MYGITHUB</h3>
        <p class="text-white">Or Maybe My Resume</p>
        <div class="cta-btn-group">
          <%= link_to "/robots.txt", class: "btn btn-orange border-none btn-rounded-corner", download: true do %>
              Download Resume<span class="icon-on-button"><i class="ion-ios-cloud-download-outline"></i></span>
          <% end %>

          <%= link_to "https://www.github.com/minhalexus", class: "btn btn-white gradient-white border-none btn-rounded-corner" do %>
              Take Me To Github<span class="icon-on-button"><i class="ion-ios-arrow-thin-right"></i></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_feature.html.erb
<section id="feature" class="padding-top-bottom-120 bg-image-fit-100" style="background:url(<%=asset_path('Elegant_Background.jpg') %>">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="heading-wraper text-center margin-bottom-25">
            <h4>Coding Problems</h4>
            <hr class="heading-devider gradient-orange">
        </div>
      </div>
      <div class="col-md-6">
        <% @problems.each do |problem| %>
          <div class="feature-wiget">
            <div class="icon-wraper">
              <h5 class="bottom-line"><i class="ion-code"></i> <%= link_to problem.name, problem %></h5>
            </div>
            <div class="content">
              <h6><%= problem.from %></h6>
              <p><%= problem.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/pages/_form.html.erb
<%= form_with(scope: @message, url: message_create_path, local: true) do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |mess| %>
        <li><%= mess %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= @message.errors.full_messages.first if @message.errors.any? %>
  <div class="form-group">
    <%= form.text_field :name, class: "form-control", placeholder:"Full Name (Required)" %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, class: "form-control", placeholder:"Email (Required)" %>
  </div>

  <div class="form-group">
    <%= form.text_area :content, class: "form-control", placeholder:"Your Message", rows:"10" %>
  </div>

  <div class="actions">
    <%= form.submit 'Send Message', class: "btn btn-orange border-none btn-rounded-corner width-70" %>
  </div>

<% end %>

app/views/pages/_github.html.erb
<section id="github" class="gradient-violat cta padding-top-bottom-90">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h3 class="cta-heading text-white">GIT CHECKOUT -B MYGITHUB</h3>
        <p class="text-white">Or Maybe My Resume</p>
        <div class="cta-btn-group">
          <%= link_to "/robots.txt", class: "btn btn-orange border-none btn-rounded-corner", download: true do %>
              Download Resume<span class="icon-on-button"><i class="ion-ios-cloud-download-outline"></i></span>
          <% end %>

          <%= link_to "https://www.github.com/minhalexus", class: "btn btn-white gradient-white border-none btn-rounded-corner" do %>
              Take Me To Github<span class="icon-on-button"><i class="ion-ios-arrow-thin-right"></i></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_introduction.html.erb
<section id="introduction" class="gradient-violat full-screen padding-top-90 home-slider website-image">
  <div class="container">
    <div class="row">
        <div class="col-md-12 center-padding">
          <h1 class="cta-heading text-white font-size-80 logo-font">MINHAL SHANJER</h2>
          <p class="text-white slider-para">ASPIRING TO CODE SOMETHING MAGICAL </p>
          <div class="cta-btn-group">
            <%= link_to "/resumeV2.pdf", class: "btn btn-orange border-none btn-rounded-corner", download: true do %>
              Download Resume<span class="icon-on-button"><i class="ion-ios-cloud-download-outline"></i></span>
            <% end %>
            
            <a class="btn btn-white border-none btn-rounded-corner" href="#about">Learn More<span class="icon-on-button"><i class="ion-ios-arrow-thin-right"></i></span></a>
          </div>
        </div>
        <div class="col-md-12 center position-bottom">
          <h6 class="text-white">University of Waterloo | Computer Science</h6>
          <h6 class="text-white">mashanje@uwaterloo.ca</h6>
        </div>
    </div>
  </div>
  <%= image_tag 'UWlogo.png', class: "uw-logo"%>
</section>

app/views/pages/_newsletter-form.html.erb
<%= form_with(scope: @emailaddress, url: add_email_path, local: true) do |form| %>
  <% if @emailaddress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emailaddress.errors.count, "error") %> prohibited this emailaddress from being saved:</h2>

      <ul>
      <% @emailaddress.errors.full_messages.each do |mess| %>
        <li><%= mess %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.text_field :email, class: "form-control", placeholder:"Email (Required)" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-orange border-none btn-rounded-corner width-70" %>
  </div>

<% end %>

app/views/pages/_projects.html.erb
<section id="projects" class="padding-top-bottom-90">
  <div class="container">
    <div class="heading-wraper text-center margin-bottom-80">
      <h4>Projects</h4>
      <hr class="heading-devider gradient-orange">
    </div>
    <div class="row">
      <% @projects.each do |project| %>
        <div class="col-md-4">
          <div class="card">
            <%= link_to project do %>
              <%= image_tag project.image, class: "card-img-top img-responsive max-width-100", alt: "Project Image" %>
            <% end %>
            <div class="card-block">
              <p class="card-text"><small class="text-muted blog-category blue-color"><%= project.language.name %></small></p>
              <h4 class="card-title center"><%= link_to project.Title, project %></h4>
              <p class="card-text character-limit-250"><%= project.Description %></p>

              <%= link_to project, class: "btn btn-link blue-color" do %>
                See More <span><i class="ion-ios-arrow-thin-right"></i></span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-md-12 padding-top-35">
        <%= link_to projects_path, class: "btn btn-blue border-none btn-rounded-corner width-archive-btn", method: :get do %>
          See Full Archive <span class="icon-on-button"><i class="ion-ios-arrow-thin-right"></i></span>
        <% end %>
      </div>
    </div>
  </div>
</section> 

app/views/pages/_skills.html.erb
<section id="skills" class="testimonial-section padding-top-bottom-90 gradient-violat">

  <div class="container">
    <div class="heading-wraper text-center">
      <h4 class="text-white">My Skills</h4>
      <hr class="heading-devider gradient-orange">
    </div>

    <% @languages.each do |language| %>
        <h5 class="text-white"> <%= language.name %> </h5>
        <div class="progress">
         <div class="progress-bar progress-bar-striped bg-success progress-bar-animated width-half" role="progressbar" aria-valuenow="<%= language.percent_understood %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= language.percent_understood %>%">
          <% if language.percent_understood <= 35 %>
              <b> BEGINNER </b>
          <% elsif language.percent_understood <= 65 %>
              <b> INTERMEDIATE </b>
          <% else %>
              <b> ADVANCED </b>
          <% end %>
         </div>
        </div>
    <% end %>
  </div>
</section>

app/views/pages/index.html.erb
<%= render "introduction" %>
<%= render "about" %>
<%= render "skills" %>
<%= render "coding-problems" %>
<%= render "projects" %>
<%= render "github" %>
<%= render "contact" %>

app/views/pages/list_messages.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 align="center text-white">Messages</h1>
    <p class="lead", align="center">You have have important messages awaiting your response!</p>
  </div>
</div>

<br>

<div class="container">
	<table class="table">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">Name</th>
	      <th scope="col">Email</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @messages.each do |message| %>
	      <tr>
	        <th scope="row"><%= message.id %></th>
	        <td><%= link_to message.name, message %></td>
	        <td><%= message.email %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

app/views/pages/show_message.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="text-white" align="center">Messages</h1>
    <p class="lead", align="center">This is a very important message.</p>
  </div>
</div>

<div class="container">
	<h5><%= @message.name %> </h5>

	<h6><%= @message.email %></h6>

	<p><%= @message.content %></p>
</div>